### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by mizraelson** [soph-liu/Slide-TCR-seq#1]
Hi, is there a chance to get the raw FASTQ files for TCR Slide-seq. I followed the link but only found R1 file with barcodes and no R2 with actual CDR3 sequences.

**Comment by soph-liu** [comment]
Yes! Thank you for bringing this to my attention, and I apologize for the delay. All of the FASTQ files have been uploaded.

**Comment by mizraelson** [comment]
Thank you!
